name: nylo_framework
description: Micro-framework for Flutter that's built to simplify app development for Flutter projects.
version: 6.9.2
homepage: https://nylo.dev
repository: https://github.com/nylo-core/framework/tree/6.x
issue_tracker: https://github.com/nylo-core/framework/issues
documentation: https://github.com/nylo-core/framework
funding:
  - https://github.com/sponsors/agordn52
topics:
  - micro-framework
  - framework

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter_dotenv: ^6.0.0
  nylo_support: ^6.38.1
  theme_provider: ^0.6.0
  flutter_secure_storage: ^10.0.0
  skeletonizer: ^2.1.1
  collection: ^1.19.1
  args: ^2.7.0
  dio: ^5.9.0
  recase: ^4.1.0
  error_stack: ^1.10.4
  date_field: ^6.0.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: The Nylo package logo.
    path: screenshots/logo.png

flutter:

