name: nylo_framework
description: Micro-framework for Flutter that's built to simplify app development for Flutter projects.
version: 6.6.2
homepage: https://nylo.dev
repository: https://github.com/nylo-core/framework/tree/6.x
issue_tracker: https://github.com/nylo-core/framework/issues
documentation: https://github.com/nylo-core/framework
funding:
  - https://github.com/sponsors/agordn52
topics:
  - micro-framework
  - framework

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter_dotenv: ^5.2.1
  nylo_support: ^6.21.0
  theme_provider: ^0.6.0
  flutter_secure_storage: ^9.2.4
  dart_console: ^4.1.1
  skeletonizer: ^1.4.3
  collection: ^1.18.0
  args: ^2.7.0
  dio: ^5.8.0+1
  recase: ^4.1.0
  error_stack: ^1.10.3
  date_field: ^6.0.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: The Nylo package logo.
    path: screenshots/logo.png

flutter:

